### ISSUE TITLE
API Update Errors?

### ISSUE THREAD

**Issue by alec-flatiron** [looker-open-source/looker_deployer#68]
Hi @drstrangelooker, we're suddenly receiving failures of ldeploy with an error mentioning missing_method `query_space`. Full log below. Wondering if this is related to GA of API 4.0. I see in our older logs the connection string built ended in 3.1. Is there something we can switch on the frontend to force our string back to referencing API 3.1? 

Full error (--- substituted for some detail)
``
[2022-03-16T16:11:51.581Z] /var/lib/gems/2.5.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:105:in `method_missing': undefined method `space' for #<LookerSDK::Client:0x000055b8a6c4dbc8> (NoMethodError)  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/modules/space.rb:65:in `query_space'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:87:in `process_space'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:81:in `block in execute'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/modules/session.rb:207:in `with_session'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:49:in `execute'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space.rb:80:in `export'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'  
[2022-03-16T16:11:51.581Z]      from /var/lib/gems/2.5.0/gems/gazer-0.2.44/exe/gzr:36:in `<top (required)>'  
[2022-03-16T16:11:51.581Z]      from /usr/local/bin/gzr:23:in `load'  
[2022-03-16T16:11:51.581Z]      from /usr/local/bin/gzr:23:in `<main>'  
[2022-03-16T16:11:51.581Z] options: {"debug"=>true, "host"=>"---", "port"=>"443", "ssl"=>true, "verify_ssl"=>true, "timeout"=>60, "force"=>false, "client_id"=>"---", "client_secret"=>"---", "dir"=>"/looker_export/Shared"}  
[2022-03-16T16:11:51.581Z] API 3.1 available? true  
[2022-03-16T16:11:51.581Z] connecting to ["api_endpoint=>https://---:443/api/4.0", "connection_options=>{:ssl=>{:verify=>true, :verify_mode=>3}, :request=>{:timeout=>60}}", "user_agent=>Gazer 0.2.44", "client_id=>---", "client_secret=>---"]  
[2022-03-16T16:11:51.581Z] check for connectivity: true  
[2022-03-16T16:11:51.581Z] verify authentication: true  
[2022-03-16T16:11:51.581Z] logout  ``

**Comment by alec-flatiron** [comment]
@JCPistell @jannarobertson-bytecode any thoughts on this? Seems like this would likely be impacting everyone

**Comment by AdamMinton** [comment]
Hi @alec-flatiron,

There was a fix applied to gzr last week related to the API 3.1 vs 4.0. https://github.com/looker-open-source/gzr/pull/125

Can you upgrade gzr and confirm if you are still experiencing the issue?

Thanks!

**Comment by alec-flatiron** [comment]
Looks like that worked for us! Pinned to the latest version. Thank you
